# Generated by Django 3.2.2 on 2021-09-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.ImageField(default='', upload_to='menus'),
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Recommend_product', '推薦商品'), ('Popular_select', '人氣精選'), ('Meal', '套餐'), ('Rice', '飯類'), ('Noodles', '麵類'), ('Side_dishes', '小菜類')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='picture',
            field=models.ImageField(default='', upload_to='stores'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
