# Generated by Django 3.2.5 on 2021-08-22 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210822_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0912-345-678'", regex='^\\d{4}\\-\\d{3}\\-\\d{3}$')]),
        ),
    ]
