# Generated by Django 3.2.2 on 2021-09-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20210915_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('Recommend_product', '推薦商品'), ('Popular_select', '人氣精選'), ('Meal', '套餐'), ('Rice', '飯類'), ('Noodles', '麵類'), ('Side_dishes', '小菜類'), ('Dessert', '點心')], default='Recommend_product', max_length=50, verbose_name='菜單類型'),
        ),
        migrations.AlterField(
            model_name='store',
            name='type',
            field=models.CharField(choices=[('Japan', '日式料理'), ('Western', '西式料理'), ('Taiwan', '台式料理'), ('America', '美式料理'), ('China', '中式料理')], default='Taiwan', max_length=10, verbose_name='店家類型'),
        ),
    ]
