# Generated by Django 3.2.2 on 2021-09-15 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_auto_20210915_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='stores.store')),
            ],
            options={
                'get_latest_by': 'pk',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.DateTimeField(verbose_name='取餐時間')),
                ('meal_local', models.CharField(max_length=50, verbose_name='取餐地點')),
                ('meal_status', models.CharField(choices=[('wait', '等待店家回應'), ('accepted', '店家接受'), ('processing', '處理中'), ('delivery', '配送中'), ('finish', '完成')], default='wait', max_length=20, verbose_name='餐點狀態')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='創建時間')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.event')),
            ],
            options={
                'unique_together': {('event', 'create_at', 'create_by')},
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_way', models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡')], default='credit_card', max_length=20, verbose_name='付款方式')),
                ('is_pay', models.BooleanField(default=False, verbose_name='付款是否成功')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay', to='orders.order', verbose_name='付款訂單')),
            ],
        ),
    ]
